name = "cybernetics-plus"
compatibility_date = "2024-02-02"

[build]
command = "npm run build"
output_dir = "dist"

[site]
bucket = "./dist"

# Enable SPA routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Configure headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"
