name = "cybernetics-plus"
type = "javascript" # or "webpack", "rust", depending on your project

[build]
command = "npm run build" # Command to build your project

[env]
pages_build_output_dir = "./dist" # Path to the build output directory
