name = "cybernetics-plus"
type = "webpack"
account_id = ""
workers_dev = true
compatibility_date = "2024-02-02"

[site]
bucket = "./dist"
entry-point = "workers-site"

[build]
command = "npm run build"
upload.format = "service-worker"

[build.upload]
format = "service-worker"

[env.production]
zone_id = ""
route = ""

# Enable SPA routing
[routes]
"/*" = "/index.html"

# Configure caching
[cache]
browser_TTL = 14400 # 4 hours
edge_TTL = 86400    # 24 hours

# Configure headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"
